services:
  - type: web
    name: mtdp-rag-openrouter
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000 --server.address 0.0.0.0
    envVars:
      - key: OPENROUTER_API_KEY
        value: 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
